benevbright/react-navigation-collapsible

LICENSE
=> ADDING MIT LICENSE

example/package-lock.json, example/package.json, example/src/ExtraHeaderScreen.js, index.js, package.json
=> fixes navigation props for extra header

.travis.yml, index.js, package-lock.json, package.json
=> add platform code for web(experimental)

index.js, package.json
Fixed #20 
When changing the drawer page, collapsible stops working.
=> Fixed #20 - When changing the drawer page, collapsible stops working.

example/.babelrc, example/package-lock.json, example/package.json, package-lock.json, package.json
=> Update example with react-native 0.57

index.js
=> support new iPhones

example/package-lock.json, example/package.json, index.js, package-lock.json, package.json
=> Fix extra Header bug that didn't render properly when height is higher than 100

index.js, package.json
=> Bug fix -#59

README.md, example/src/S1_ExtraHeader.js, example/src/S3_ExtraHeaderForTab.js, index.js
=> Add option for disabling Face out effect on inner component.

README.md, index.js
```
const collapsibleParams = {
collapsibleComponent: SearchBar,
collapsibleBackgroundStyle: {
height: 60, 
backgroundColor: 'red',
paddingBottom: 2,
}
}
```
This closes #66
=> Add 'paddingBottom' for extra collapsible component style.

example/App.tsx, example/babel.config.js, example/metro.config.js, example/src/Collapsible.tsx, example/src/DetailScreen.tsx, example/src/S1-RegularHeaderScreen.tsx, index.ts, index.tsx, package.json, tsconfig.json, yarn.lock
=> Migrate the lib for v5 (normal stack)

src/createCollapsibleStack.tsx
Related to #110 
Working well by encapsulate positionY on ref
=> Making working with TabNavigator

README.md, example/src/DefaultHeaderScreen.tsx, src/createCollapsibleStack.tsx, src/hooks.ts, src/types.ts
=> Add listerner option for onScroll

README.md, index.ts, src/utils.ts
=> Add Expo option to disable statusbar calculation

README.md, src/createCollapsibleStack.tsx, src/types.ts
=> Pass React key through the config

index.js
Allow dynamic set header height.
=> add set header height function

README.md
It should be "Collapsible" not "Callapsible"
=> fix: small change in README.md

example/App.tsx, src/CollapsedHeaderBackground.tsx, src/utils.ts
=> Fix elevation crash

README.md, example/src/BackgroundHeaderScreen.tsx, example/src/CustomHeaderScreen.tsx, example/src/DefaultHeaderScreen.tsx, example/src/StickyHeaderScreen.tsx, src/core.tsx
This refactoring is needed to scale up this library. 
Sorry about that.
=> Refactoring parameters (Breaking change)

src/core.tsx
For now, `showHeader()` changes `positionY` directly, this causes header flashes back its hidden state while scrolling right after `showHeader()` because `onScroll` event will override this value from far.
I'm introducing a new attribute `offsetY`, this value is not affected by `onScroll` and can offset position.
We can simply show header by subtracting `headerHeight` from `offsetY`, and `offsetY` also can be animated.
=> feat: add offset value for showing header smoothly
